include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_lambdas: true
    always_use_package_imports: true

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

