// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDVe9AY1DcgCPHSqPx_yQbXpO1_kV02dM',
    appId: '1:499162431381:web:31509d0f90312a0972409c',
    messagingSenderId: '499162431381',
    projectId: 'smartreceipt-8faff',
    authDomain: 'smartreceipt-8faff.firebaseapp.com',
    storageBucket: 'smartreceipt-8faff.firebasestorage.app',
    measurementId: 'G-QVCVSDPV3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg6iKOOiXwpNJEYKK7kKFPFaKnNLp56cQ',
    appId: '1:499162431381:android:f596aeba1d9f8d8572409c',
    messagingSenderId: '499162431381',
    projectId: 'smartreceipt-8faff',
    storageBucket: 'smartreceipt-8faff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXFLJH57vga2ybOAPFiw_McG2MkXYWAr4',
    appId: '1:499162431381:ios:78d3b2c8a1a7a50872409c',
    messagingSenderId: '499162431381',
    projectId: 'smartreceipt-8faff',
    storageBucket: 'smartreceipt-8faff.firebasestorage.app',
    iosBundleId: 'com.vaibhs.smartreceipt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXFLJH57vga2ybOAPFiw_McG2MkXYWAr4',
    appId: '1:499162431381:ios:f31cee95b582d15072409c',
    messagingSenderId: '499162431381',
    projectId: 'smartreceipt-8faff',
    storageBucket: 'smartreceipt-8faff.firebasestorage.app',
    iosBundleId: 'n',
  );

}